import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Container, Theme } from '@radix-ui/themes';
import SideBar from './SideBar';
import AuthProvider from './auth/provider';
import UserAvatar from './UserAvatar';
import { getServerSession } from 'next-auth';
import { useEffect, useState } from 'react';
import LoadingScreen from './components/LoadingScreen';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <AuthProvider>
          <Theme appearance="light" accentColor="teal" radius="large">
            <div className="flex">
              <SideBar />
              <main>
                <UserAvatar />
                <Container className="ml-20 md:ml-0 pt-5">{children}</Container>
              </main>
            </div>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
